In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web

In [60]:
import datetime

In [61]:
start = datetime.datetime(2019,1,1)
end = datetime.datetime(2020,1,1)

In [62]:
x = web.DataReader('V','yahoo',start = start,end = end)['Adj Close']

In [63]:
portfolio

,MSFT,AAPL,AMZN,GOOG,GOOGL,FB,JNJ,V,PG,JPM,UNH,MA,INTC,VZ,HD,T,PFE,MRK,PEP
Date,,,,,,,,,,,,,,,,,,,
2018-12-31,99.540192,154.340271,1501.969971,1035.609985,1044.959961,131.089996,123.858055,130.690369,87.735100,92.194786,242.874496,186.817291,45.001755,52.227005,165.166473,25.593552,40.851418,73.192429,105.756058
2019-01-02,99.099190,154.516388,1539.130005,1045.849976,1054.680054,135.679993,122.610352,131.661087,87.124245,93.790855,237.385666,187.896744,45.145596,52.041206,165.733612,26.490316,40.477058,72.406944,104.607376
2019-01-03,95.453529,139.125412,1500.280029,1016.059998,1025.469971,131.740005,120.662025,126.916458,86.513382,92.457924,230.912094,179.419876,42.662006,52.227005,162.080765,26.526182,39.344639,70.922234,103.630989
2019-01-04,99.893005,145.064575,1575.390015,1070.709961,1078.069946,137.949997,122.687134,132.384171,88.279152,95.866432,233.612671,187.916519,45.279839,52.357067,166.896759,27.207722,40.243088,73.058311,105.756058
2019-01-07,100.020401,144.741714,1629.510010,1068.390015,1075.920044,138.050003,121.900124,134.771347,87.926003,95.933067,234.061142,189.362335,45.490799,52.691494,170.184296,27.700937,40.458340,72.253700,104.846680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-24,156.515396,282.322266,1789.209961,1343.560059,1344.430054,205.119995,144.007080,186.985657,122.880356,133.990799,292.011993,296.229370,58.390232,59.337166,217.902313,37.135822,38.136204,89.975586,134.924606
2019-12-26,157.798309,287.923645,1868.770020,1360.400024,1362.469971,207.789993,143.908401,188.570694,122.880356,135.412704,293.112457,297.942139,58.793194,59.346851,218.050446,37.326458,38.223560,89.877182,134.727478
2019-12-27,158.086731,287.814392,1869.800049,1351.890015,1354.640015,208.100006,143.829453,188.799973,123.734093,135.510101,293.429718,299.475647,59.048733,59.579243,217.211090,37.402714,38.165321,90.034622,135.565262
2019-12-30,156.724243,289.522614,1846.890015,1336.140015,1339.709961,204.410004,143.385391,187.244843,122.144363,135.013397,291.327911,296.468323,58.596626,59.269386,214.584442,37.212074,37.767365,89.572151,134.845749
2019-12-31,156.833633,291.638000,1847.839966,1337.020020,1339.390015,205.250000,143.947876,187.314606,122.566338,135.763306,291.456818,297.334686,58.822678,59.453365,215.641037,37.250202,38.029430,89.493423,134.707764

In [64]:
tickers = ['MSFT','AAPL','AMZN','GOOG','GOOGL','FB','JNJ','V','PG','JPM','UNH','MA','INTC','VZ','HD','T','PFE','MRK','PEP']
portfolio =pd.DataFrame(columns = tickers,index =x.index )
for ticker in tickers:
    try:
        portfolio[ticker] = web.DataReader(ticker,'yahoo',start = start,end = end)['Adj Close']
    except:
        print('cant get info for {}'.format(ticker))

In [65]:
portfolio_returns = portfolio.pct_change()

In [77]:
def portfolio_stats(weights):
    
    '''
    We can gather the portfolio performance metrics for a specific set of weights.
    This function will be important because we'll want to pass it to an optmization
    function to get the portfolio with the best desired characteristics.
    
    Note: Sharpe ratio here uses a risk-free short rate of 0.
    
    Paramaters: 
    -----------
        weights: array, 
            asset weights in the portfolio.
        returns: dataframe
            a dataframe of returns for each asset in the trial portfolio    
    
    Returns: 
    --------
        dict of portfolio statistics - mean return, volatility, sharp ratio.
    '''

    # Convert to array in case list was passed instead.
    weights = np.array(weights)
    port_return = np.sum(portfolio_returns.mean() * weights) * 252
    port_vol = np.sqrt(np.dot(weights.T, np.dot(portfolio_returns.cov() * 252, weights)))
    sharpe = port_return/port_vol

    return {'return': port_return, 'volatility': port_vol, 'sharpe': sharpe}

In [78]:
num_assets = len(portfolio.columns)

In [79]:
def minimize_volatility(weights):  
    # Note that we don't return the negative of volatility here because we 
    # want the absolute value of volatility to shrink, unlike sharpe.
    return portfolio_stats(weights)['volatility']

In [80]:
constraints = ({'type' : 'eq', 'fun': lambda x: np.sum(x) -1})
bounds = tuple((0,1) for x in range(num_assets))
initializer = num_assets * [1./num_assets,]

print (initializer)
print (bounds)

[0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842]
((0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1))

In [82]:
import scipy.optimize as optimize
optimal_volatilty=optimize.minimize(minimize_volatility,
                                 initializer,
                                 method = 'SLSQP',
                                 bounds = bounds,
                                 constraints = constraints)

In [88]:
x = pd.DataFrame(optimal_volatilty.x,index = portfolio_returns.columns)

In [94]:
x.columns = ['Weight of Asset']

In [98]:
x['Weight of Asset'].sort_values(ascending = False)[0:5]

PEP    0.172702
VZ     0.170095
JNJ    0.146257
JPM    0.108991
PG     0.091584
Name: Weight of Asset, dtype: float64